### ISSUE TITLE
Improve usability of ethereum actions if MetaMask is disabled

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-i#102]
If MetaMask is disabled, we only prompt the user to enable it. We should make it easier for the user to use an alternate wallet by (for example) providing copy-to-clipboard buttons and a confirmation functionality like the one we use for bitcoin actions (see #101).

Questions:
- How should we handle the case where MetaMask is enabled but the user wants to use a different wallet without bloating the action dialog with buttons and options?

Furthermore, when MetaMask is enabled and the user attempts to send a transaction without logging into their account, the action fails without providing feedback as to what the user should do about the error. The intention was to fix this in #104, but Web3/MetaMask don't provide good enough errors to handle specific cases like this one.

**Comment by D4nte** [comment]
>     * How should we handle the case where MetaMask is enabled but the user wants to use a different wallet without bloating the action dialog with buttons and options?

I think it is reasonable to assume that if the user wants a different wallet, he will easier use a browser without metamask or deactivate metamask.
So far, I have not encountered any dapp that offers you to use an alternate wallet if metamask is here.

**Comment by thomaseizinger** [comment]
> How should we handle the case where MetaMask is enabled but the user wants to use a different wallet without bloating the action dialog with buttons and options?

Since only one of those at a time make sense, we could use `Tabs`. Each tab could be one form of execution:

- Manual
- Metamask
- Ledger Nano S
- ...

As a bonus feature, you could remember in localStorage, which one the user did the last time and re-select that one initially. But that is a separate issue if we actually go for it.
