### ISSUE TITLE
User behavior tracking

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-i#111]
We should add a some logging into comit-i to track what the user is doing, e.g. heat maps where he is clicking, tracing of how far does he go in the process of sending/accepting swap requests, etc.

We should gather this information somewhere online centrally so that we can evaluate user behavior.

Tool: Google Analytics
Implementation: Add a popup upon the first launch of comit-i (use cookies for that), that explains that we are tracking and why we are doing it.
No option to opt-out so far.

Activities we want to track:
* user creates a new link (click on the tab, click through the form and fill out the fields, click send)
* user send swap request after clicking on a link
* user creates link

In general we are interested in 
* the time to action, i.e. the time it takes him to fill out a form and submits the form, 
* how he is clicking through the web interface

**Comment by tcharding** [comment]
If we decide to do this all data should be open i.e. all data collection done in an open manner and all collected data (and aggregation) easily available online.
