### ISSUE TITLE
Adapt to updated action type `ethereum-call-contract`

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-i#43]
Update comit-i as per below
Dod:
- [x] `ethereum-invoke-contract` is now `ethereum-call-contract`
- [x] amount field is removed from this action type

**Comment by D4nte** [comment]
@luckysori you apparently half-started this issue in your current PR. Maybe worth doing all of it in one go?

**Comment by luckysori** [comment]
> @luckysori you apparently half-started this issue in your current PR. Maybe worth doing all of it in one go?

Good point! Will do!
