### ISSUE TITLE
Ensure comit-i works with comit-rs again

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-i#46]
as the title implies.

DoD:
- [ ] do a simple swap ETH_BTC

**Comment by D4nte** [comment]
Shan't we try all combinations?

**Comment by luckysori** [comment]
I have tested one direction successfully. I also decided to document the process of setting up and doing the swap:

# Set up

1.  Two comit nodes running
    -   `COMIT_NODE_CONFIG_PATH="./api_tests/regtest/alice/" ./target/debug/comit_node`
    -   `COMIT_NODE_CONFIG_PATH="./api_tests/regtest/bob/" ./target/debug/comit_node`
    -   Run from comit-rs
2.  One comit-i running, swap comit node it talks to via settings
    -   `yarn run start`
    -   In settings page to connect to Alice's node set:
        1.  Host: localhost
        2.  Port: 8000
    -   The values of host and port may change depending on the comit node config file used
3.  One btsieve
    -   `BTSIEVE_CONFIG_PATH="./api_tests/regtest/btsieve" ./target/debug/btsieve`
    -   Run from comit-rs
4.  Bitcoin node
    -   `docker-compose up btc` from comit-rs/api<sub>tests</sub>/regtest
    -   `docker-exec -it regtest_btc_1 sh` (name of container may differ)
5.  Ethereum node
    -   `docker run -p 8545:8545 --volume $(pwd):/src parity/parity:stable --chain=/src/parity-config.json --jsonrpc-cors=all --jsonrpc-apis=all --jsonrpc-interface=all`
    -   Run from directory with parity-config.json file
6.  Metamask
    -   Network: localhost:8545
    -   Open Metamask using your own account's password

# BTC-ETH swap

1.  As Alice, send swap request using comit-i
    -   Example ethereum address for redeem identity: 0x540f3e485765c9260f197cb7e386cbafb4e27d6e
        -   Can also run `cargo run -p key_gen` from comit-rs
    -   Get Bob's peer id from logs
2.  As Bob, accept swap request
3.  As Alice, fund bitcoin
    1.  Click on fund action to obtain a bitcoin address and an amount (in satoshi)
    2.  Inside regtest<sub>btc</sub><sub>1</sub> container, activate segwit using `bitcoin-cli -regtest generate 500`
    3.  Fund using `bitcoin-cli -regtest sendtoaddress <address> <amount-in-bitcoin>`
    4.  Generate one block: `bitcoin-cli -regtest generate 1`
4.  As Bob, deploy and fund ethereum
    1.  Click on fund action to obtain a contract and an amount
    2.  Click on send transaction Metamask button and confirm
5.  As Alice, redeem ethereum
    1.  Click on redeem action to obtain contract address and contract data
    2.  Click on send transaction Metamask button to invoke contract and confirm
6.  As Bob, redeem bitcoin
    1.  Click on redeem action
    2.  Fill in Bob's redeem bitcoin address and the fee per byte (e.g. 20)
    3.  Copy signed transaction to clipboard
    4.  Broadcast signed transaction: `bitcoin-cli sendrawtransaction <copied-signed-transaction>`
    5.  Generate a block: `bitcoin-cli -regtest generate 1`

**Comment by bonomat** [comment]
The notes above might be relevant for comit-network/comit-rs#919.
