### ISSUE TITLE
Clear RFC003 identity text field when ledger select changes

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-i#48]
Example:

1. Fill out form with bitcoin as alpha ledger and ethereum as beta ledger.
2. Select RFC003 as protocol and fill out parameters including Beta Redeem Identity.
3. Swap bitcoin and ethereum, making ethereum the alpha ledger and bitcoin the beta ledger.
4. Now fill out Alpha Refund Identity RFC003 protocol parameter.
5. Fill out peer ID and click the send button.

This will fail because the Beta Redeem Identity field is not cleared when the ledgers are swapped, meaning that an unexpected field is sent to the comit node as part of the swap request.

**Comment by D4nte** [comment]
@luckysori we know use ZenHub. Please install the ZenHub browser extension and add this to the transparent comit-i Epic :)

**Comment by LLFourn** [comment]
@D4nte Fixing bugs in comit-i is now "transparent comit-i"? :smile:

**Comment by thomaseizinger** [comment]
As long as the bugfix makes it more transparent, it sure is!

**Comment by D4nte** [comment]
> @D4nte Fixing bugs in comit-i is now "transparent comit-i"? 😄

Then someone add a BUG label.
