### ISSUE TITLE
Handling disabled actions

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-i#49]
Disabling a button until refund is available is currently not possible for bitcoin (and [eventually ethereum too](https://github.com/comit-network/spikes/blob/master/0002-ether-htlc-dynamic-final-addresses.md)), because the user has to provide a bitcoin address and a fee per byte before the action with the `min_median_block_time` is even returned.  

For usability purposes it would be nice to disable the button, which would require one of these things to happen:

1. Actions to be pre-loaded when swaps are listed.
2. The "invalid_until" timestamp to be included with the action href in `GET /swaps`.

For 1. @thomaseizinger suggested automatically filling in the fields required to fetch an action using a configuration file in `comit-rs`.

**Comment by thomaseizinger** [comment]
What do you guys think about having some kind of _source_ in `comit-i` as well that allows to pre-fill fields?

I am thinking of the following here:
- bitcoin-address: BIP32
- fee_per_byte: fixed value (to start with)
- ethereum-address: fixed value (to start with)

**Comment by bonomat** [comment]
Decision: no disabling of buttons for now because the user should always be able to actually get the action payload.

Also, what should be disabled is the broadcasting of the transaction.
