### ISSUE TITLE
Pre-loading actions

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-i#54]
Certain actions such as `bitcoin-broadcast-signed-transaction` (redeeming or refunding on Bitcoin) can only be fetched by providing parameters in the GET request, requiring an extra step. It would be cleaner to fetch these actions directly.

@thomaseizinger [already had some ideas about this](https://github.com/comit-network/comit-i/issues/49#issuecomment-490365513):
>What do you guys think about having some kind of source in comit-i as well that allows to pre-fill fields?
>
>I am thinking of the following here:
>
>bitcoin-address: BIP32
> fee_per_byte: fixed value (to start with)
> ethereum-address: fixed value (to start with)

**Comment by D4nte** [comment]
No because we do not want to store/allow user to pre-configure addresses just yet.
