### ISSUE TITLE
Peer ID overflows generated link preview

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-i#55]
The peer ID we now use overflows the generated link preview in the "Create swap link" page.

![May16::122548](https://user-images.githubusercontent.com/9418575/57847216-3a84d000-77d6-11e9-8e32-fabad14ca408.png)

Play with some solutions.

**Comment by thomaseizinger** [comment]
http://2.bp.blogspot.com/-41v6n3Vaf5s/UeRN_XJ0keI/AAAAAAAAN2Y/YxIHhddGiaw/s1600/css.gif
