### ISSUE TITLE
Action dialogs do not enforce required fields

### ISSUE THREAD

**Issue by luckysori** [comit-network/comit-i#67]
Action dialogs may be going away, but if they're not it would be good to prevent actions from being performed if all the required fields are not filled in.

The fields are correctly marked as required but this is not enforced and we instead rely on the comit node failing to process the incomplete action. No feedback is given to the user when it fails, other than nothing happening.

**Comment by thomaseizinger** [comment]
We are going to enforce this by using a `form` and a `submit` button :)
