### ISSUE TITLE
Support ip in link and swap request

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-i#68]
See comit-network/comit-rs#883

DoD:
- [x] Support new link format: `peer=<id>[@multiaddress]` when creating a link
- [x] Support new link format: `peer=<id>[@multiaddress]` when reading a link
- [x] Use address in swap request as per changes done with comit-network/comit-rs#883

**Comment by D4nte** [comment]
@comit-network/rust-devs the result, due to URI encoding, is:
`web+comit://swap?peer=QmXfGiwNESAFWUvDVJ4NLaKYYVopYdV5HbpDSgz5TSypkb%40%2Fip4%2F1.2.3.4.5%2Ftcp%2F9000`

for `QmXfGiwNESAFWUvDVJ4NLaKYYVopYdV5HbpDSgz5TSypkb@/ip4/1.2.3.4/tcp/9000`. Are we happy with that?

**Comment by thomaseizinger** [comment]
Do we have much choice? :)
