### ISSUE TITLE
Work around the fact the executed ledger actions don't result in an immediate state update of the comit_node

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-i#75]
Currently, executing ledger actions in comit-i is not atomically coupled to a state update on the comit_node.

This is because we directly broadcast transaction from comit-i and the comit_node only learns about them through btsieve.

As a result, if the user executes a ledger action, they still see the same buttons as before because the currently available actions are derived from the state the comit_node returns.

This represents a usability issue. The user might think executing the action didn't work and possibly do it again. For actions like `Fund` this might result in the user sending more money to the HTLC than initially intended.

Eventually, this issue could be resolved by making the comit_node aware of L1 and sending the client-generated TX to the comit_node instead of broadcasting the TX directly from the client. That allows the comit_node to couple the state update to the execution of the action.

---
Proposed solution: 
- If possible, get and store transaction id (e.g. Metamask)
- Otherwise, make the user confirm that they did it: For bitcoin, we should now display 2 buttons ("cancel" and "Yes, I did it!")

If they click "yes, I did it!", then:
- The action disappears from the ListSwaps page
- In the swap details page, the action is still available with an added subtext/note/warning "You said you already did it" (up to implementer for the details).

**Comment by D4nte** [comment]
Feedback:
- impractical to input txid if user uses a mobile wallet
- not sure the feature is needed, especially with lack of error handling
- User should be able to do it again
